import {nextCronRun} from '../lib/triggers.js';

const input = 'min-h-11 w-full rounded-md border border-slate-300 bg-white px-2 text-base text-slate-900 focus:outline-none focus:ring-2 focus:ring-cyan-500 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100';
const action = 'min-h-11 min-w-11 rounded-md border border-slate-300 px-2 text-base font-bold hover:border-cyan-500 focus:outline-none focus:ring-2 focus:ring-cyan-500 dark:border-slate-700';

function clockMeta(cue, now) {
  if (!cue.cron?.trim()) return '—';
  const next = nextCronRun(cue.cron, now);
  if (!next) return 'invalid cron';
  return `next ${next.toLocaleTimeString([], {hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false})}`;
}

export function MobileCueCards({cues, groups, now, onChange, onBlurCommand, onInsert, onMove, onRemove}) {
  return <div className="space-y-3 border-t border-slate-200 p-3 dark:border-slate-800" data-testid="mobile-cue-cards">
    {cues.map((cue, index) => <article key={cue.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3 shadow-sm dark:border-slate-700 dark:bg-slate-950/40" aria-label={`Cue ${index + 1} card`}>
      <div className="mb-3 flex items-center justify-between gap-2"><span className={`rounded-full px-2 py-1 text-sm font-bold ${cue.status === 'LIVE' ? 'bg-amber-100 text-amber-800' : cue.status === 'DONE' ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-700'}`}>{cue.status}</span><span aria-label={`${cue.type === 'audio' ? 'Audio' : cue.type === 'trigger' ? 'Trigger' : 'Command'} cue`} className="text-sm">{cue.type === 'audio' ? '♪' : cue.type === 'trigger' ? '↪' : '⌘'}</span><span className="text-sm font-bold text-slate-500">CUE {index + 1}</span></div>
      <div className="grid gap-3">
        <label className="text-sm font-bold text-slate-500">Name<input className={`${input} mt-1`} aria-label={`Name for cue ${index + 1}`} value={cue.name} onChange={event => onChange(cue.id, {name: event.target.value})}/></label>
        <label className="text-sm font-bold text-slate-500">Type<select className={`${input} mt-1`} aria-label={`Type for cue ${index + 1}`} value={cue.type} onChange={event => onChange(cue.id, {type: event.target.value, audioAction: event.target.value === 'audio' ? 'play' : cue.audioAction, targetGroupName: '', targetCueName: ''})}><option value="command">Command</option><option value="trigger">Trigger cue</option><option value="audio">Audio</option></select></label>
        {cue.type === 'trigger' ? <div className="grid gap-3"><label className="text-sm font-bold text-slate-500">Target group<select className={`${input} mt-1`} aria-label={`Target group for cue ${index + 1}`} value={cue.targetGroupName} onChange={event => onChange(cue.id, {targetGroupName: event.target.value, targetCueName: ''})}><option value="">Target group…</option>{groups.map(group => <option key={group.id} value={group.name}>{group.name}</option>)}</select></label><label className="text-sm font-bold text-slate-500">Target cue<select className={`${input} mt-1`} aria-label={`Target cue for cue ${index + 1}`} value={cue.targetCueName} onChange={event => onChange(cue.id, {targetCueName: event.target.value})}><option value="">Target cue…</option>{groups.find(group => group.name === cue.targetGroupName)?.cues.map(target => <option key={target.id} value={target.name}>{target.name}</option>)}</select></label></div> : cue.type === 'audio' ? <label className="text-sm font-bold text-slate-500">Audio action<select className={`${input} mt-1`} aria-label={`Audio action for cue ${index + 1}`} value={cue.audioAction} onChange={event => onChange(cue.id, {audioAction: event.target.value})}><option value="play">Play</option><option value="pause">Pause</option><option value="stop">Stop</option></select></label> : <label className="text-sm font-bold text-slate-500">Command<input className={`${input} mt-1`} aria-label={`Command for cue ${index + 1}`} value={cue.command} onChange={event => onChange(cue.id, {command: event.target.value})} onBlur={() => onBlurCommand(cue.id)}/></label>}
        <div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold text-slate-500">Hotkey<input className={`${input} mt-1`} maxLength={1} aria-label={`Hotkey for cue ${index + 1}`} value={cue.hotkey} onChange={event => onChange(cue.id, {hotkey: event.target.value.slice(0, 1)})}/></label><label className="text-sm font-bold text-slate-500">LTC trigger<input className={`${input} mt-1`} aria-label={`LTC trigger for cue ${index + 1}`} placeholder="01:00:00:00" value={cue.ltcTrigger} onChange={event => onChange(cue.id, {ltcTrigger: event.target.value})}/></label></div>
        <label className="text-sm font-bold text-slate-500">Cron<input className={`${input} mt-1`} aria-label={`Cron for cue ${index + 1}`} placeholder="* * * * * *" value={cue.cron} onChange={event => onChange(cue.id, {cron: event.target.value})}/><span className="mt-1 block font-mono text-sm font-normal">{clockMeta(cue, now)}</span></label>
        <div className="grid grid-cols-2 gap-3"><label className="text-sm font-bold text-slate-500">Before-wait (ms)<input className={`${input} mt-1`} type="number" min="0" aria-label={`Before-wait for cue ${index + 1}`} value={cue.beforeWaitMs} onChange={event => onChange(cue.id, {beforeWaitMs: Math.max(0, Number(event.target.value) || 0)})}/></label><label className="text-sm font-bold text-slate-500">After-wait (ms)<input className={`${input} mt-1`} type="number" min="0" aria-label={`After-wait for cue ${index + 1}`} value={cue.afterWaitMs} onChange={event => onChange(cue.id, {afterWaitMs: Math.max(0, Number(event.target.value) || 0)})}/></label></div>
      </div>
      <div className="mt-3 flex gap-2"><button className={action} aria-label={`Insert after cue ${index + 1}`} onClick={() => onInsert(index)}>+</button><button className={action} aria-label={`Move cue ${index + 1} up`} onClick={() => onMove(index, -1)}>↑</button><button className={action} aria-label={`Move cue ${index + 1} down`} onClick={() => onMove(index, 1)}>↓</button><button className={`${action} text-rose-600`} aria-label={`Delete cue ${index + 1}`} onClick={() => onRemove(cue.id)}>×</button></div>
    </article>)}
  </div>;
}
